import type { Metadata } from "next";
import Link from "next/link";
import { CONTACT_EMAIL, LegalPage } from "@/components/legal-page";

export const metadata: Metadata = { title: "Terms of Service" };

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="9 October 2026">
      <section>
        <p>By creating a FitForge account or using the site, you agree to these terms. Please read them.</p>
      </section>

      <section>
        <h2>Not medical advice</h2>
        <p>
          FitForge, including its AI-generated workout plans, diet plans and coach replies, gives general fitness and
          nutrition guidance only. It is not medical advice and does not replace a doctor, physiotherapist or registered
          dietitian. Talk to a medical professional before starting a new exercise or diet programme, especially if you
          are pregnant, have an injury, or have a medical condition. Stop exercising and seek help if you feel pain,
          dizziness or shortness of breath.
        </p>
      </section>

      <section>
        <h2>AI-generated content</h2>
        <p>
          Plans and coach replies are generated by AI and can be wrong or unsuitable for you. Use your own judgement
          and do not follow any suggestion that feels unsafe.
        </p>
      </section>

      <section>
        <h2>Your account</h2>
        <ul>
          <li>You must be at least 18 years old to use FitForge.</li>
          <li>Give accurate information and keep your password safe. You are responsible for activity on your account.</li>
          <li>You can delete your account at any time from Settings.</li>
        </ul>
      </section>

      <section>
        <h2>Acceptable use</h2>
        <p>
          Don&apos;t misuse the service. That includes trying to access other people&apos;s data, overloading or
          attacking the service, scraping it, or using the AI coach to produce harmful content. We may suspend accounts
          that do.
        </p>
      </section>

      <section>
        <h2>Your content</h2>
        <p>
          You own what you put into FitForge: your logs, photos and messages. You give us permission to store and
          process it only to run the service for you. If you submit a testimonial, you allow us to show it, with the
          name you provided, on our website.
        </p>
      </section>

      <section>
        <h2>Pricing</h2>
        <p>
          FitForge is currently free. The Pro plan shown on the site is not yet available. Joining the waitlist does not
          charge you or commit you to anything.
        </p>
      </section>

      <section>
        <h2>No guarantees</h2>
        <p>
          We work to keep FitForge available and accurate, but the service is provided &quot;as is&quot;. We don&apos;t
          guarantee specific results, and to the extent the law allows, we are not liable for injuries, losses or
          damages arising from your use of the service.
        </p>
      </section>

      <section>
        <h2>Changes</h2>
        <p>
          We may update these terms. We will change the date at the top of this page, and for significant changes we
          will let you know by email.
        </p>
      </section>

      <section>
        <h2>Contact</h2>
        <p>
          Questions? Email <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>. See also our{" "}
          <Link href="/privacy">Privacy Policy</Link>.
        </p>
      </section>
    </LegalPage>
  );
}
